import {
  IconBell,
  IconBuilding,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconCreditCard,
  IconDeviceLaptop,
  IconDots,
  IconEdit,
  IconEye,
  IconFolder,
  IconGrid3x3,
  IconHome,
  IconInfoCircle,
  IconLoader2,
  IconLogout,
  IconMenu2,
  IconMoon,
  IconPalette,
  IconPhoto,
  IconPlus,
  IconSearch,
  IconSettings,
  IconShield,
  IconSun,
  IconTrash,
  IconUpload,
  IconUser,
  IconUserPlus,
  IconUsers,
  IconX,
} from "@tabler/icons-react";

export const Icons = {
  home: IconHome,
  users: IconUsers,
  user: IconUser,
  plus: IconPlus,
  settings: IconSettings,
  search: IconSearch,
  trash: IconTrash,
  folder: IconFolder,
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  menu: IconMenu2,
  close: IconX,
  spinner: IconLoader2,
  logout: IconLogout,
  edit: IconEdit,
  grid: IconGrid3x3,
  image: IconPhoto,
  upload: IconUpload,
  moreVertical: IconDots,
  eye: IconEye,
  shield: IconShield,
  userPlus: IconUserPlus,
  palette: IconPalette,
  laptop: IconDeviceLaptop,
  moon: IconMoon,
  sun: IconSun,
  bell: IconBell,
  check: IconCheck,
  creditCard: IconCreditCard,
  building: IconBuilding,
  info: IconInfoCircle,
} as const;

export type IconName = keyof typeof Icons;
