import {
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconEdit,
  IconFolder,
  IconGrid3x3,
  IconHome,
  IconLoader2,
  IconLogout,
  IconMenu2,
  IconPhoto,
  IconPlus,
  IconSearch,
  IconSettings,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconX,
} from "@tabler/icons-react";

export const Icons = {
  home: IconHome,
  users: IconUsers,
  user: IconUser,
  plus: IconPlus,
  settings: IconSettings,
  search: IconSearch,
  trash: IconTrash,
  folder: IconFolder,
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  menu: IconMenu2,
  close: IconX,
  spinner: IconLoader2,
  logout: IconLogout,
  edit: IconEdit,
  grid: IconGrid3x3,
  image: IconPhoto,
  upload: IconUpload,
} as const;

export type IconName = keyof typeof Icons;
